# Generated by Django 5.2.8 on 2025-11-25 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "saldo_atual",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("corrente", "corrente"),
                            ("poupanca", "poupanca"),
                            ("cartao", "cartao"),
                        ],
                        default="corrente",
                        max_length=20,
                    ),
                ),
                ("cor", models.CharField(blank=True, max_length=20, null=True)),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
