# Generated by Django 5.2.8 on 2025-11-25 19:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transacao",
            name="compra_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="transacao",
            name="parcela_atual",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transacao",
            name="parcelas_totais",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
