# Generated by Django 5.2.8 on 2025-11-25 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("finances", "0002_transacao_compra_uuid_transacao_parcela_atual_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transacao",
            name="conta",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.account",
            ),
            preserve_default=False,
        ),
    ]
