# Generated by Django 5.2.8 on 2025-11-25 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0003_transacao_conta"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transacao",
            name="tipo",
        ),
    ]
